### ISSUE TITLE
Broken link on Usage page

### ISSUE THREAD

**Issue by glapa-grossklag** [vprover/vprover.github.io#5]
The link on the following line leads to a 404:

https://github.com/vprover/vprover.github.io/blob/e34b6a36f488d1b0188ee6bb2a0a78c66b7a5ea4/usage.html#L20

**Comment by MichaelRawson** [comment]
Thanks! Sorry for the considerable delay. We ended up putting this information in the usage section of the README, website will be given some attention shortly.
